name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
      - uses: cypress-io/github-action@v4.2.9
      -  uses: actions/setup-node@v2
          with:
            node-version: '16'
        - name: Test the project
          run: |
            npm run dev
            cd client
            npm start
           
         # use the explicit version number
      